import type { ButtonHandler } from '../../../types/component.js';
import { demoHelloButton } from './demoHello.js';
import { actionLogsHomeButton, actionLogsPageButton } from './actionLogs.js';
import {
  settingsAutoNextButton,
  settingsAutoPrevButton,
  settingsBackButton,
  settingsClearRolesButton
} from './settingsAutoRoles.js';
import {
  settingsCountriesBackButton,
  settingsCountriesEditButton,
  settingsCountriesFirstButton,
  settingsCountriesLastButton,
  settingsCountriesNextButton,
  settingsCountriesTabButton,
  settingsCountriesResetButton,
  settingsCountriesPrevButton
} from './settingsCountries.js';
import { serverTabsButton } from './serverTabs.js';
import { mutesPageButton } from './mutes.js';
import { registrationBackButton, registrationPageButton } from './registrationNavigation.js';
import { profileEditButton } from './profile.js';
import {
  companyFinanceBranchesBackButton,
  companyFinanceBranchesButton,
  companyFinanceBranchesInfoButton,
  companyFinanceBranchesNextButton,
  companyFinanceBranchesPrevButton,
  companyFinanceBranchesStartButton,
  companyFinanceRedomicileBackButton,
  companyFinanceRedomicileConfirmButton,
  companyFinanceRedomicileEditButton,
  companyFinanceRedomicileInfrastructureBuildButton,
  companyFinanceRedomicileInfrastructureDoneButton,
  companyFinanceRedomicileInfrastructureStartButton,
  companyFinanceRedomicileInteractionOpenButton,
  companyFinanceRedomicileJurisdictionDoneButton,
  companyFinanceRedomicileJurisdictionStartButton,
  companyFinanceRedomicileOpenButton,
  companyFinanceFeeEditButton,
  companyFinanceCryptoExchangeBackButton,
  companyFinanceCryptoExchangeInfrastructureBuildButton,
  companyFinanceCryptoExchangeInfrastructureOpenButton,
  companyFinanceCryptoExchangeLegalDoneButton,
  companyFinanceCryptoExchangeLegalStartButton,
  companyFinanceCryptoExchangeWebOpenButton,
  companyFinanceCryptoExchangeWebOrderButton,
  companyFinanceConstructionBackButton,
  companyFinanceConstructionEquipmentBuyButton,
  companyFinanceConstructionEquipmentOpenButton,
  companyFinanceConstructionLegalDoneButton,
  companyFinanceConstructionLegalStartButton,
  companyFinanceConstructionWebOpenButton,
  companyFinanceConstructionWebOrderButton,
  companyFinanceInvestmentExchangeBackButton,
  companyFinanceInvestmentExchangeInfrastructureBuildButton,
  companyFinanceInvestmentExchangeInfrastructureOpenButton,
  companyFinanceInvestmentExchangeLegalDoneButton,
  companyFinanceInvestmentExchangeLegalStartButton,
  companyFinanceInvestmentExchangeWebOpenButton,
  companyFinanceInvestmentExchangeWebOrderButton,
  companyFinanceManufacturingBackButton,
  companyFinanceManufacturingEquipmentBuyButton,
  companyFinanceManufacturingEquipmentOpenButton,
  companyFinanceManufacturingInfrastructureBuildButton,
  companyFinanceManufacturingInfrastructureOpenButton,
  companyFinanceManufacturingLegalDoneButton,
  companyFinanceManufacturingLegalStartButton,
  companyFinancePaymentSystemBackButton,
  companyFinancePaymentSystemInfrastructureBuildButton,
  companyFinancePaymentSystemInfrastructureOpenButton,
  companyFinancePaymentSystemLegalDoneButton,
  companyFinancePaymentSystemLegalStartButton,
  companyFinancePaymentSystemWebOpenButton,
  companyFinancePaymentSystemWebOrderButton,
  financeBudgetBackButton,
  financeBudgetButton,
  financeForeignTaxEditButton,
  financeResidentTaxEditButton,
  financeTaxationCollectButton,
  financeTaxationEditButton
} from './finance.js';
import {
  companyCountryBackButton,
  companyCountryPageButton,
  companyCreateButton,
  companyEditCountryButton,
  companyEditIndustryButton,
  companyEditNameButton,
  companyEntryExistingButton,
  companyEntryNewButton,
  companyExistingBackButton,
  companyExistingPageButton
} from './companyRegistration.js';
import { ownerPanelResetCompaniesButton, ownerPanelResetCountriesButton } from './ownerPanel.js';
import { marryAcceptButton, marryDivorceButton, marryRejectButton } from './marry.js';
import { topPageButton } from './top.js';

export const buttonHandlers: ButtonHandler[] = [
  demoHelloButton,
  actionLogsPageButton,
  actionLogsHomeButton,
  settingsBackButton,
  settingsClearRolesButton,
  settingsAutoPrevButton,
  settingsAutoNextButton,
  settingsCountriesBackButton,
  settingsCountriesEditButton,
  settingsCountriesFirstButton,
  settingsCountriesPrevButton,
  settingsCountriesNextButton,
  settingsCountriesLastButton,
  settingsCountriesTabButton,
  settingsCountriesResetButton,
  serverTabsButton,
  mutesPageButton,
  registrationBackButton,
  registrationPageButton,
  companyEditNameButton,
  companyEntryNewButton,
  companyEntryExistingButton,
  companyEditIndustryButton,
  companyEditCountryButton,
  companyCreateButton,
  companyCountryBackButton,
  companyCountryPageButton,
  companyExistingBackButton,
  companyExistingPageButton,
  profileEditButton,
  financeBudgetButton,
  financeBudgetBackButton,
  financeTaxationEditButton,
  financeResidentTaxEditButton,
  financeForeignTaxEditButton,
  financeTaxationCollectButton,
  companyFinanceBranchesButton,
  companyFinanceBranchesInfoButton,
  companyFinanceBranchesStartButton,
  companyFinanceFeeEditButton,
  companyFinanceRedomicileOpenButton,
  companyFinanceRedomicileBackButton,
  companyFinanceRedomicileEditButton,
  companyFinanceRedomicileJurisdictionStartButton,
  companyFinanceRedomicileJurisdictionDoneButton,
  companyFinanceRedomicileInfrastructureStartButton,
  companyFinanceRedomicileInfrastructureBuildButton,
  companyFinanceRedomicileInfrastructureDoneButton,
  companyFinanceRedomicileInteractionOpenButton,
  companyFinanceRedomicileConfirmButton,
  companyFinanceInvestmentExchangeBackButton,
  companyFinanceInvestmentExchangeLegalStartButton,
  companyFinanceInvestmentExchangeLegalDoneButton,
  companyFinanceInvestmentExchangeInfrastructureOpenButton,
  companyFinanceInvestmentExchangeInfrastructureBuildButton,
  companyFinanceInvestmentExchangeWebOpenButton,
  companyFinanceInvestmentExchangeWebOrderButton,
  companyFinanceCryptoExchangeBackButton,
  companyFinanceCryptoExchangeLegalStartButton,
  companyFinanceCryptoExchangeLegalDoneButton,
  companyFinanceCryptoExchangeInfrastructureOpenButton,
  companyFinanceCryptoExchangeInfrastructureBuildButton,
  companyFinanceCryptoExchangeWebOpenButton,
  companyFinanceCryptoExchangeWebOrderButton,
  companyFinanceConstructionBackButton,
  companyFinanceConstructionLegalStartButton,
  companyFinanceConstructionLegalDoneButton,
  companyFinanceConstructionEquipmentOpenButton,
  companyFinanceConstructionEquipmentBuyButton,
  companyFinanceConstructionWebOpenButton,
  companyFinanceConstructionWebOrderButton,
  companyFinancePaymentSystemBackButton,
  companyFinancePaymentSystemLegalStartButton,
  companyFinancePaymentSystemLegalDoneButton,
  companyFinancePaymentSystemInfrastructureOpenButton,
  companyFinancePaymentSystemInfrastructureBuildButton,
  companyFinancePaymentSystemWebOpenButton,
  companyFinancePaymentSystemWebOrderButton,
  companyFinanceManufacturingBackButton,
  companyFinanceManufacturingLegalStartButton,
  companyFinanceManufacturingLegalDoneButton,
  companyFinanceManufacturingInfrastructureOpenButton,
  companyFinanceManufacturingInfrastructureBuildButton,
  companyFinanceManufacturingEquipmentOpenButton,
  companyFinanceManufacturingEquipmentBuyButton,
  companyFinanceBranchesBackButton,
  companyFinanceBranchesPrevButton,
  companyFinanceBranchesNextButton,
  ownerPanelResetCountriesButton,
  ownerPanelResetCompaniesButton,
  marryAcceptButton,
  marryRejectButton,
  marryDivorceButton,
  topPageButton
];